services:
  postgres_tallyweb:
    restart: always
    env_file:
      - .env
    image: "postgres"
    network: tallyweb
    ports: 
      - 5442:5432
    volumes:
      - ./postgresql:/var/lib/postgresql

  tallyweb:
    restart: always
    image: "p3rtang/tallyweb"
    network: tallyweb
    ports:
      - 3000:3000

  tallyweb-dev:
    restart: always
    image: "p3rtang/tallyweb:dev"
    network: tallyweb
    ports:
      - 3050:3000

networks:
  tallyweb
