[package]
name = "components"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
leptos = { version = "0.5", features = ["nightly"] }
leptos_router = { version = "0.5.1", features = ["nightly"] }
wasm-bindgen = "=0.2.87"
js-sys = "0.3.64"
web-sys = { version = "0.3.64", features = ["Storage", "Element", "Document"] }
rand = "0.8.5"
