name: Docker Image CI

on:
  push:
    branches: [ "development" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: create .env-docker
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env-docker
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env-docker
    - name: Build docker
      run: docker build . --tag p3rtang/tallyweb:dev --build-arg OUT_NAME="tallyweb_$(tr -dc a-z0-9 </dev/urandom | head -c 10)"
    - name: Push docker
      run: docker push p3rtang/tallyweb:dev
