name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker
      env: 
        IDB_TALLYWEB_VERSION: ${{ vars.IDB_TALLYWEB_VERSION }}
      run: docker build . --tag p3rtang/tallyweb
    - name: Push docker
      run: docker push p3rtang/tallyweb
