name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
<<<<<<< HEAD
=======
  services:
    postgres:
      image: postgres
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
      env:
        POSTGRES_PASSWORD: ${{ end2end.POSTGRES_PASSWORD }}
      ports:
        - 5432:5432

>>>>>>> a2cd9d3 (e2e: add secrets)
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install leptos
      run: cargo install cargo-leptos
    - name: Add wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Setup postgres from test dump
      run: psql -U p3rtang -d tally_web -f .github/postgres_setup/test_dump.sql
    - name: Run Playwright tests
      run: cargo leptos end-to-end -r
      with:
        env:
          DATABASE_URL: ${{ end2end.DATABASE_URL }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
